fixed links in keep track of notebooks
neptune-ai/docs pull request #115
Opened 2020-10-16 14:03 UTC by jakubczakon

2020-10-18 18:11 UTC, kamil-kaczmarek submitted a review, later dismissed
Looks good!

2020-10-18 18:16 UTC, kamil-kaczmarek requested changes
One link does not work (check comment).
Besides this looks good!

2020-10-18 18:16 UTC, kamil-kaczmarek commented on docs/keep-track-of-jupyter-notebooks/index.rst
> +    <a href="https://ui.neptune.ai/shared/onboarding/n/neural-style-tutorial-c96dce51-409a-4b1b-8dbf-c47d52868d9b/9a7f6736-8794-44f0-9060-cf1b451d92d9" target="_blank">share a Notebook</a>
This link leads to 404 error

2020-10-19 15:21 UTC, jakubczakon commented on docs/keep-track-of-jupyter-notebooks/index.rst
> +    <a href="https://ui.neptune.ai/shared/onboarding/n/neural-style-tutorial-c96dce51-409a-4b1b-8dbf-c47d52868d9b/9a7f6736-8794-44f0-9060-cf1b451d92d9" target="_blank">share a Notebook</a>
fixed/updated

2020-10-19 15:26 UTC, kamil-kaczmarek commented on docs/keep-track-of-jupyter-notebooks/index.rst
> +    <a href="https://ui.neptune.ai/shared/onboarding/n/neural-style-tutorial-c96dce51-409a-4b1b-8dbf-c47d52868d9b/9a7f6736-8794-44f0-9060-cf1b451d92d9" target="_blank">share a Notebook</a>
I see that it works now.

2020-10-19 15:46 UTC, kamil-kaczmarek approved these changes

2020-10-19 15:47 UTC, merged